#!/bin/bash

set -e

if [ -z "$1" ]; then
    echo "Usage: kubeconfig ENV"
    exit 1
fi

ENV_DIR=$1
ENV=$(basename $ENV_DIR)

pushd $ENV_DIR/actions-runner-aks
KUBECONFIG=$(mktemp)
terraform output -raw kube_config_raw > $KUBECONFIG
popd

echo "Run the following before using kubectl, helm etc. :"
echo "export KUBECONFIG=$KUBECONFIG"
