#! /bin/bash

set -e

if [ -z "$3" ]; then
    echo "Usage: replace-crt ENV CRT_FILE KEY_FILE"
    exit 1
fi

ENV_DIR=$1
ENV=$(basename $ENV_DIR)
CRT_FILE=$2
KEY_FILE=$3

pushd $ENV_DIR/configuration
VAULT_NAME=$(terraform output --raw key_vault_name)
popd

az keyvault secret set --vault-name $VAULT_NAME --name web-ui-crt --file $CRT_FILE --encoding ascii
az keyvault secret set --vault-name $VAULT_NAME --name web-ui-crt-key --file $KEY_FILE --encoding ascii